version: '3.7'

services:
  database_toptrampo:
    image: postgres
    container_name: database_toptrampo
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=toptrampo
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: toptrampo
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host


volumes:
  pgdata: 
    driver: local