# version: '3.7'

# services:
#   database_toptrampo:
#     image: postgres
#     container_name: database_toptrampo
#     restart: always
#     ports: 
#       - 5432:5432
#     environment:
#       - POSTGRES_USER=docker
#       - POSTGRES_PASSWORD=root
#       - POSTGRES_DB=toptrampo
#     volumes:
#       - pgdata:/data/postgres
#     links:
#       - database
#     depends_on: 
#       - database
#   app:
#     build: .
#     container_name: toptrampo
#     ports:
#       - 3333:3333
#     volumes:
#       - .:/usr/app
#     links:
#       - database
#     depends_on: 
#       - database


# volumes:
#   pgdata: 
#     driver: local

version: "3.7"

services:
  database: 
    image: postgres
    container_name: database_toptrampo
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=toptrampo
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: toptrampo
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local